
std_msgs/Header header

uint16 group_fields
raptor_msgs/ImuStatus imustatus
geometry_msgs/Vector3 uncompmag
geometry_msgs/Vector3 uncompaccel
geometry_msgs/Vector3 uncompgyro
float32 temperature
float32 pressure
raptor_msgs/DeltaTheta deltatheta
geometry_msgs/Vector3 deltavel
geometry_msgs/Vector3 mag
geometry_msgs/Vector3 accel
geometry_msgs/Vector3 angularrate
raptor_msgs/SensSat senssat

